# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('place', models.CharField(max_length=256)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
