# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0005_auto_20170618_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='nameAndSurname',
            field=models.CharField(default='', max_length=256),
        ),
    ]
