# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0006_auto_20170618_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='location',
            name='distanceBg',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='distanceNis',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='distanceNs',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='location',
            name='place',
            field=models.CharField(default='', max_length=256),
        ),
    ]
