# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0007_auto_20170624_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('email', models.CharField(default='', max_length=256)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
