# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='availableRooms',
            field=models.IntegerField(default=0),
        ),
    ]
