# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0009_appartment_availablerooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='photo',
            field=models.CharField(default=0, max_length=1024),
        ),
    ]
