# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppartmentRent', '0010_appartment_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartment',
            name='photo',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
